export const nfts = [
  {
    id: 1,
    title: "Battle for Digital",
    description:
      "A stunning piece exploring the intersection of nature and technology. This 1 of 1 edition represents the constant struggle for dominance in our evolving digital landscape.",
    image: "/abstract-digital-art-with-flowers.jpg",
    creator: "Waiano Akarana",
    creatorImage: "/diverse-profile-avatars.png",
    auction: 0.0008, // Starting bid ETH
    buyNow: 0.0015, // ETH
    likes: 19,
    currentBid: 0.0011, // ETH
    currentBidUSD: 3.30,
    buyNowPrice: 0.0015, // ETH
    buyNowPriceUSD: 4.50,
    serviceFeeUSD: 0.25,
    auctionEndsIn: { hours: 18, minutes: 42, seconds: 5 },
  },
  {
    id: 2,
    title: "A Rare Path",
    description:
      "A meditative geometric landscape representing the unpredictability of the creative journey.",
    image: "/purple-pink-abstract-cube-design.jpg",
    creator: "Waiano Akarana",
    creatorImage: "/diverse-profile-avatars.png",
    auction: 0.0010,
    buyNow: 0.00166,
    likes: 20,
    currentBid: 0.0014,
    currentBidUSD: 4.20,
    buyNowPrice: 0.00166,
    buyNowPriceUSD: 5.00, // Max Price capped at $5
    serviceFeeUSD: 0.30,
    auctionEndsIn: { hours: 7, minutes: 25, seconds: 31 },
  },
  {
    id: 3,
    title: "Software Secret Algorithms",
    description:
      "An artistic visualization of machine learning layers and the hidden biases within algorithms.",
    image: "/abstract-white-cloud-formation.jpg",
    creator: "Waiano Akarana",
    creatorImage: "/diverse-profile-avatars.png",
    auction: 0.0005,
    buyNow: 0.0010,
    likes: 12,
    currentBid: 0.0007,
    currentBidUSD: 2.10,
    buyNowPrice: 0.0010,
    buyNowPriceUSD: 3.00,
    serviceFeeUSD: 0.15,
    auctionEndsIn: { hours: 3, minutes: 56, seconds: 9 },
  },
  {
    id: 4,
    title: "Blazeon Killer",
    description:
      "Bold contrasts of red and gold portray the aggression of digital dominance in the blockchain era.",
    image: "/gradient-sphere-abstract-art.jpg",
    creator: "Waiano Akarana",
    creatorImage: "/diverse-profile-avatars.png",
    auction: 0.0009,
    buyNow: 0.0016,
    likes: 15,
    currentBid: 0.0012,
    currentBidUSD: 3.60,
    buyNowPrice: 0.0016,
    buyNowPriceUSD: 4.80,
    serviceFeeUSD: 0.28,
    auctionEndsIn: { hours: 22, minutes: 11, seconds: 50 },
  },
  {
    id: 5,
    title: "Wait Before Buying",
    description:
      "A symbolic pause on consumerism — this minimalistic art asks the viewer to reflect before acting.",
    image: "/cloudy-abstract-landscape.jpg",
    creator: "Waiano Akarana",
    creatorImage: "/diverse-profile-avatars.png",
    auction: 0.0006,
    buyNow: 0.0012,
    likes: 8,
    currentBid: 0.0008,
    currentBidUSD: 2.40,
    buyNowPrice: 0.0012,
    buyNowPriceUSD: 3.60,
    serviceFeeUSD: 0.20,
    auctionEndsIn: { hours: 11, minutes: 8, seconds: 44 },
  },
  {
    id: 6,
    title: "Repeal of Online Privacy",
    description:
      "A glitch-inspired work symbolizing how digital transparency can sometimes mean exposure.",
    image: "/layered-abstract-shapes-sunset.jpg",
    creator: "Waiano Akarana",
    creatorImage: "/diverse-profile-avatars.png",
    auction: 0.0007,
    buyNow: 0.0014,
    likes: 11,
    currentBid: 0.0010,
    currentBidUSD: 3.00,
    buyNowPrice: 0.0014,
    buyNowPriceUSD: 4.20,
    serviceFeeUSD: 0.22,
    auctionEndsIn: { hours: 5, minutes: 59, seconds: 12 },
  },
];