export const nfts = [
  {
    id: 1,
    title: "Battle for Digital",
    description:
      "A stunning piece exploring the intersection of nature and technology. This 1 of 1 edition represents the constant struggle for dominance in our evolving digital landscape.",
    image: "/abstract-digital-art-with-flowers.jpg",
    creator: "Waiano Akarana",
    creatorImage: "/diverse-profile-avatars.png",
    auction: 2.0,
    buyNow: 14.5,
    likes: 19,
    currentBid: 2.6,
    currentBidUSD: 4350.12,
    buyNowPrice: 14.5,
    buyNowPriceUSD: 24387.5,
    serviceFeeUSD: 35.0,
    auctionEndsIn: { hours: 18, minutes: 42, seconds: 5 },
  },
  {
    id: 2,
    title: "A Rare Path",
    description:
      "A meditative geometric landscape representing the unpredictability of the creative journey.",
    image: "/purple-pink-abstract-cube-design.jpg",
    creator: "Waiano Akarana",
    creatorImage: "/diverse-profile-avatars.png",
    auction: 2.5,
    buyNow: 18.5,
    likes: 20,
    currentBid: 3.1,
    currentBidUSD: 5192.5,
    buyNowPrice: 18.5,
    buyNowPriceUSD: 30972.5,
    serviceFeeUSD: 42.0,
    auctionEndsIn: { hours: 7, minutes: 25, seconds: 31 },
  },
  {
    id: 3,
    title: "Software Secret Algorithms",
    description:
      "An artistic visualization of machine learning layers and the hidden biases within algorithms.",
    image: "/abstract-white-cloud-formation.jpg",
    creator: "Waiano Akarana",
    creatorImage: "/diverse-profile-avatars.png",
    auction: 1.2,
    buyNow: 9.9,
    likes: 12,
    currentBid: 1.45,
    currentBidUSD: 2430.38,
    buyNowPrice: 9.9,
    buyNowPriceUSD: 16582.5,
    serviceFeeUSD: 22.0,
    auctionEndsIn: { hours: 3, minutes: 56, seconds: 9 },
  },
  {
    id: 4,
    title: "Blazeon Killer",
    description:
      "Bold contrasts of red and gold portray the aggression of digital dominance in the blockchain era.",
    image: "/gradient-sphere-abstract-art.jpg",
    creator: "Waiano Akarana",
    creatorImage: "/diverse-profile-avatars.png",
    auction: 2.75,
    buyNow: 29.0,
    likes: 15,
    currentBid: 3.8,
    currentBidUSD: 6365.0,
    buyNowPrice: 29.0,
    buyNowPriceUSD: 48575.0,
    serviceFeeUSD: 55.0,
    auctionEndsIn: { hours: 22, minutes: 11, seconds: 50 },
  },
  {
    id: 5,
    title: "Wait Before Buying",
    description:
      "A symbolic pause on consumerism — this minimalistic art asks the viewer to reflect before acting.",
    image: "/cloudy-abstract-landscape.jpg",
    creator: "Waiano Akarana",
    creatorImage: "/diverse-profile-avatars.png",
    auction: 1.9,
    buyNow: 15.0,
    likes: 8,
    currentBid: 2.1,
    currentBidUSD: 3517.5,
    buyNowPrice: 15.0,
    buyNowPriceUSD: 25125.0,
    serviceFeeUSD: 27.0,
    auctionEndsIn: { hours: 11, minutes: 8, seconds: 44 },
  },
  {
    id: 6,
    title: "Repeal of Online Privacy",
    description:
      "A glitch-inspired work symbolizing how digital transparency can sometimes mean exposure.",
    image: "/layered-abstract-shapes-sunset.jpg",
    creator: "Waiano Akarana",
    creatorImage: "/diverse-profile-avatars.png",
    auction: 2.1,
    buyNow: 17.2,
    likes: 11,
    currentBid: 2.4,
    currentBidUSD: 4020.0,
    buyNowPrice: 17.2,
    buyNowPriceUSD: 28810.0,
    serviceFeeUSD: 31.0,
    auctionEndsIn: { hours: 5, minutes: 59, seconds: 12 },
  },
];
